version: "2.4"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/node/app
      - /node/app/node_modules
